version: '3.8'

services:
  wh_sim23_backend:
    build: ./backend
    container_name: wh_sim23_backend
    restart: always
    volumes:
      - ./backend/db:/app/db  # 持久化 SQLite 数据库文件
      - ./backend/static:/app/staticfiles
    ports:
      - "5004:8000"  # 重点：左边是外面访问的端口，右边是容器内的端口
    environment:
      - DEBUG=False

  wh_sim23_frontend:
    build: ./frontend
    container_name: wh_sim23_frontend
    restart: always
    ports:
      - "5003:80"  # 服务器 5003 -> 容器 80
    depends_on:
      - wh_sim23_backend

networks:
  default:
    name: wh_sim23_network