version: '3.8'

services:
  wh_sim23_backend:
    build: ./backend
    container_name: wh_sim23_backend
    restart: always
    volumes:
      - ./backend/db:/app/db  # 持久化 SQLite 数据库文件
      - ./backend/static:/app/staticfiles
    environment:
      - DEBUG=False

  wh_sim23_frontend:
    build: ./frontend
    container_name: wh_sim23_frontend
    restart: always
    ports:
      - "8081:80"  # 服务器 8081 -> 容器 80
    depends_on:
      - wh_sim23_backend

networks:
  default:
    name: wh_sim23_network