# Generated by Django 5.2.8 on 2026-04-21 16:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Client Name")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
            ],
            options={
                "verbose_name": "Client",
                "verbose_name_plural": "Clients",
                "db_table": "wms_client",
            },
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Location Name"
                    ),
                ),
                (
                    "zone",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Location Zone",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("STORAGE", "Storage"),
                            ("DOCK", "Dock"),
                            ("PACKING", "Packing"),
                            ("PICKING", "Picking"),
                            ("BULK", "Bulk"),
                        ],
                        default="PICKING",
                        max_length=50,
                        verbose_name="Location Type",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
            ],
            options={
                "verbose_name": "Location",
                "verbose_name_plural": "Locations",
                "db_table": "wms_location",
            },
        ),
        migrations.CreateModel(
            name="Warehouse",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Warehouse Name"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        unique=True,
                        verbose_name="Warehouse Code",
                    ),
                ),
                (
                    "zone",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Zone"
                    ),
                ),
                (
                    "address1",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Address 1"
                    ),
                ),
                (
                    "address2",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Address 2"
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Country"
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="State/Province",
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="City"
                    ),
                ),
                (
                    "postal_code",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Postal Code"
                    ),
                ),
                (
                    "time_zone",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Time Zone"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Phone"
                    ),
                ),
                (
                    "fax",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Fax"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="Email"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("ACTIVE", "Active"), ("INACTIVE", "Inactive")],
                        default="ACTIVE",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
            ],
            options={
                "verbose_name": "Warehouse",
                "verbose_name_plural": "Warehouses",
                "db_table": "wms_warehouse",
            },
        ),
        migrations.CreateModel(
            name="OutboundOrder",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "order_number",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Order Number"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PROCESSING", "Processing"),
                            ("SHIPPED", "Shipped"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "customer_name",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Customer Name (Ship-To)",
                    ),
                ),
                (
                    "warehouse_name",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Ship-From Warehouse",
                    ),
                ),
                (
                    "transaction_id",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Transaction ID",
                    ),
                ),
                (
                    "purchase_order",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Purchase Order (PO)",
                    ),
                ),
                (
                    "earliest_ship_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Earliest Ship Date"
                    ),
                ),
                (
                    "ship_cancel_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Ship Cancel Date"
                    ),
                ),
                (
                    "contact_code",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Contact Code",
                    ),
                ),
                (
                    "recipient_name",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Recipient Name",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Phone"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="Email"
                    ),
                ),
                (
                    "address1",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Address 1"
                    ),
                ),
                (
                    "address2",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Address 2"
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Country"
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="State/Province",
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="City"
                    ),
                ),
                (
                    "postal_code",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Postal Code"
                    ),
                ),
                (
                    "retailer_id",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Retailer ID",
                    ),
                ),
                (
                    "department_number",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Department Number",
                    ),
                ),
                (
                    "total_packages",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Total Packages"
                    ),
                ),
                (
                    "packaging_uom",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Packaging UOM",
                    ),
                ),
                (
                    "total_weight",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=12,
                        null=True,
                        verbose_name="Total Weight",
                    ),
                ),
                (
                    "total_volume",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=12,
                        null=True,
                        verbose_name="Total Volume",
                    ),
                ),
                (
                    "carrier",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Carrier"
                    ),
                ),
                (
                    "scac",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="SCAC Code"
                    ),
                ),
                (
                    "service",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Service Type",
                    ),
                ),
                (
                    "billing_type",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Billing Type",
                    ),
                ),
                (
                    "account_number",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Account Number",
                    ),
                ),
                (
                    "account_zip",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Account Zip Code",
                    ),
                ),
                (
                    "tracking_number",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Tracking Number",
                    ),
                ),
                (
                    "warehouse_instructions",
                    models.TextField(
                        blank=True, null=True, verbose_name="Warehouse Instructions"
                    ),
                ),
                (
                    "carrier_instructions",
                    models.TextField(
                        blank=True, null=True, verbose_name="Carrier Instructions"
                    ),
                ),
                (
                    "load_number",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Load Number",
                    ),
                ),
                (
                    "bol_number",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="BOL Number"
                    ),
                ),
                (
                    "trailer_number",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Trailer Number",
                    ),
                ),
                (
                    "seal_number",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Seal Number",
                    ),
                ),
                (
                    "door",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Door"
                    ),
                ),
                (
                    "capacity_type",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Capacity Type",
                    ),
                ),
                (
                    "pickup_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Pickup Date"
                    ),
                ),
                (
                    "require_return_receipt",
                    models.BooleanField(
                        default=False, verbose_name="Require Return Receipt"
                    ),
                ),
                (
                    "saturday_delivery",
                    models.BooleanField(
                        default=False, verbose_name="Saturday Delivery"
                    ),
                ),
                (
                    "residential_delivery",
                    models.BooleanField(
                        default=False, verbose_name="Residential Delivery"
                    ),
                ),
                (
                    "insurance",
                    models.BooleanField(default=False, verbose_name="Insurance"),
                ),
                (
                    "insurance_type",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Insurance Type",
                    ),
                ),
                (
                    "insurance_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Insurance Amount",
                    ),
                ),
                (
                    "delivery_confirmation",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Delivery Confirmation",
                    ),
                ),
                (
                    "dry_weight",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Dry Weight"
                    ),
                ),
                (
                    "intl_contents_type",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="International Contents Type",
                    ),
                ),
                (
                    "intl_non_delivery",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="International Non-Delivery Instructions",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to="warehouses.client",
                        verbose_name="Client",
                    ),
                ),
            ],
            options={
                "verbose_name": "Outbound Order",
                "verbose_name_plural": "Outbound Orders",
                "db_table": "wms_outbound_order",
            },
        ),
        migrations.CreateModel(
            name="OrderCharge",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "origin",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Charge Origin",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Category"
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Label"
                    ),
                ),
                (
                    "per_unit",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Price Per Unit",
                    ),
                ),
                (
                    "units",
                    models.IntegerField(blank=True, null=True, verbose_name="Units"),
                ),
                (
                    "total",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Total",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="charges",
                        to="warehouses.outboundorder",
                        verbose_name="Order",
                    ),
                ),
            ],
            options={
                "verbose_name": "Order Charge",
                "verbose_name_plural": "Order Charges",
                "db_table": "wms_order_charge",
            },
        ),
        migrations.CreateModel(
            name="Sku",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "part_number",
                    models.CharField(max_length=100, verbose_name="Part Number (SKU)"),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "track_by",
                    models.CharField(
                        default="NONE", max_length=50, verbose_name="Track By"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skus",
                        to="warehouses.client",
                        verbose_name="Client",
                    ),
                ),
            ],
            options={
                "verbose_name": "SKU",
                "verbose_name_plural": "SKUs",
                "db_table": "wms_sku",
                "unique_together": {("client", "part_number")},
            },
        ),
        migrations.CreateModel(
            name="OutboundOrderItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("qty", models.IntegerField(verbose_name="Quantity Ordered")),
                (
                    "picked_qty",
                    models.IntegerField(default=0, verbose_name="Quantity Picked"),
                ),
                (
                    "uom",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="UOM"
                    ),
                ),
                (
                    "volume",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=10,
                        null=True,
                        verbose_name="Volume",
                    ),
                ),
                (
                    "weight",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=10,
                        null=True,
                        verbose_name="Weight",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Unit Price",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="warehouses.outboundorder",
                        verbose_name="Order",
                    ),
                ),
                (
                    "sku",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="outbound_order_items",
                        to="warehouses.sku",
                        verbose_name="SKU",
                    ),
                ),
            ],
            options={
                "verbose_name": "Order Item",
                "verbose_name_plural": "Order Items",
                "db_table": "wms_outbound_order_item",
            },
        ),
        migrations.CreateModel(
            name="InventoryTransaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("INBOUND", "Inbound"),
                            ("OUTBOUND", "Outbound"),
                            ("TRANSFER", "Transfer"),
                            ("ADJUSTMENT", "Adjustment"),
                        ],
                        max_length=50,
                        verbose_name="Transaction Type",
                    ),
                ),
                ("change_qty", models.IntegerField(verbose_name="Change Quantity")),
                (
                    "reference_id",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Reference ID",
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Reason"
                    ),
                ),
                (
                    "serial_number",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Serial Number",
                    ),
                ),
                (
                    "lot_number",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Lot Number"
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="Timestamp"),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="warehouses.client",
                        verbose_name="Client",
                    ),
                ),
                (
                    "from_bin",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transactions_from",
                        to="warehouses.location",
                        verbose_name="From Location",
                    ),
                ),
                (
                    "to_bin",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transactions_to",
                        to="warehouses.location",
                        verbose_name="To Location",
                    ),
                ),
                (
                    "sku",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="transactions",
                        to="warehouses.sku",
                        verbose_name="SKU",
                    ),
                ),
            ],
            options={
                "verbose_name": "Inventory Transaction",
                "verbose_name_plural": "Inventory Transactions",
                "db_table": "wms_inventory_transaction",
            },
        ),
        migrations.AddField(
            model_name="location",
            name="warehouse",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="locations",
                to="warehouses.warehouse",
                verbose_name="Warehouse",
            ),
        ),
        migrations.CreateModel(
            name="Inventory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "qty",
                    models.IntegerField(default=0, verbose_name="On-hand Quantity"),
                ),
                (
                    "serial_number",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Serial Number",
                    ),
                ),
                (
                    "lot_number",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Lot Number"
                    ),
                ),
                (
                    "expiry_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Expiry Date"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Last Updated"),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventory",
                        to="warehouses.client",
                        verbose_name="Client",
                    ),
                ),
                (
                    "bin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="inventory",
                        to="warehouses.location",
                        verbose_name="Location",
                    ),
                ),
                (
                    "sku",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="inventory",
                        to="warehouses.sku",
                        verbose_name="SKU",
                    ),
                ),
            ],
            options={
                "verbose_name": "Inventory",
                "verbose_name_plural": "Inventory Details",
                "db_table": "wms_inventory",
                "unique_together": {("sku", "bin", "serial_number", "lot_number")},
            },
        ),
    ]
