# Generated by Django 5.2.8 on 2026-05-01 05:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouses", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventory",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Created At / Receipt Date",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="sku",
            name="allocation_method",
            field=models.CharField(
                choices=[
                    ("FIFO", "First In First Out (Earliest Received First)"),
                    ("FEFO", "First Expired First Out (Earliest Expiry First)"),
                    ("PICKPATH", "Shortest Pick Path (Nearest Location First)"),
                ],
                default="FIFO",
                max_length=20,
                verbose_name="Allocation Strategy",
            ),
        ),
    ]
