# Generated by Django 5.2.13 on 2026-04-22 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0002_client_address1_client_address2_client_alias_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='warehouses',
            field=models.ManyToManyField(blank=True, related_name='clients', to='warehouses.warehouse', verbose_name='Accessible Warehouses'),
        ),
    ]
