# Generated by Django 5.2.8 on 2026-05-05 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouses", "0002_inventory_created_at_sku_allocation_method"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="cancel_reason",
            field=models.TextField(blank=True, null=True),
        ),
    ]
