# Generated by Django 5.2.13 on 2026-04-22 06:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0003_client_warehouses'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=20, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='location',
            name='allocation_priority',
            field=models.IntegerField(default=10, verbose_name='Allocation Priority'),
        ),
        migrations.AddField(
            model_name='location',
            name='billing_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Billing Type'),
        ),
        migrations.AddField(
            model_name='location',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Location Description'),
        ),
        migrations.AddField(
            model_name='location',
            name='height',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Height'),
        ),
        migrations.AddField(
            model_name='location',
            name='is_non_pickable',
            field=models.BooleanField(default=False, verbose_name='Non-pickable'),
        ),
        migrations.AddField(
            model_name='location',
            name='length',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Length'),
        ),
        migrations.AddField(
            model_name='location',
            name='max_weight',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Max Weight'),
        ),
        migrations.AddField(
            model_name='location',
            name='min_quantity',
            field=models.IntegerField(default=0, verbose_name='Min Quantity'),
        ),
        migrations.AddField(
            model_name='location',
            name='min_temperature',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Min Temperature'),
        ),
        migrations.AddField(
            model_name='location',
            name='pick_path',
            field=models.IntegerField(default=0, verbose_name='Pick Path'),
        ),
        migrations.AddField(
            model_name='location',
            name='width',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Width'),
        ),
        migrations.AddField(
            model_name='outboundorder',
            name='created_by',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='location',
            name='type',
            field=models.CharField(choices=[('STORAGE', 'Storage location'), ('STAGING', 'Staging location'), ('PUTAWAY', 'Put-away vehicle'), ('QUARANTINE', 'Quarantine'), ('PICKLINE', 'PickLine')], default='STORAGE', max_length=50, verbose_name='Location Type Identifier'),
        ),
        migrations.AlterField(
            model_name='ordercharge',
            name='origin',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Origin'),
        ),
        migrations.AlterField(
            model_name='ordercharge',
            name='per_unit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Per Unit'),
        ),
        migrations.AlterField(
            model_name='outboundorder',
            name='account_zip',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Account Zip'),
        ),
        migrations.AlterField(
            model_name='outboundorder',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='warehouses.client', verbose_name='Customer'),
        ),
        migrations.AlterField(
            model_name='outboundorder',
            name='customer_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Customer Name'),
        ),
        migrations.AlterField(
            model_name='outboundorder',
            name='intl_contents_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Intl Contents Type'),
        ),
        migrations.AlterField(
            model_name='outboundorder',
            name='intl_non_delivery',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Intl Non Delivery'),
        ),
        migrations.AlterField(
            model_name='outboundorder',
            name='order_number',
            field=models.CharField(max_length=100, unique=True, verbose_name='Reference Number'),
        ),
        migrations.AlterField(
            model_name='outboundorder',
            name='scac',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='SCAC'),
        ),
        migrations.AlterField(
            model_name='outboundorder',
            name='service',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Service'),
        ),
        migrations.AlterField(
            model_name='outboundorder',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='outboundorder',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('SHIPPED', 'Shipped'), ('COMPLETE', 'Complete'), ('CLOSED', 'Closed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='outboundorder',
            name='warehouse_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Warehouse Name'),
        ),
        migrations.AlterField(
            model_name='outboundorderitem',
            name='picked_qty',
            field=models.IntegerField(default=0, verbose_name='Picked Quantity'),
        ),
        migrations.AlterField(
            model_name='outboundorderitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='outboundorderitem',
            name='qty',
            field=models.IntegerField(verbose_name='Quantity'),
        ),
    ]
