# Generated by Django 5.2.13 on 2026-04-22 06:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0004_client_status_location_allocation_priority_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventory',
            options={'verbose_name': 'Inventory', 'verbose_name_plural': 'Inventory Records'},
        ),
        migrations.AlterField(
            model_name='inventory',
            name='bin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='inventory', to='warehouses.location', verbose_name='Bin Location'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='qty',
            field=models.IntegerField(default=0, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='inventorytransaction',
            name='change_qty',
            field=models.IntegerField(verbose_name='Quantity Changed'),
        ),
        migrations.AlterField(
            model_name='inventorytransaction',
            name='from_bin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions_from', to='warehouses.location', verbose_name='From Bin'),
        ),
        migrations.AlterField(
            model_name='inventorytransaction',
            name='to_bin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions_to', to='warehouses.location', verbose_name='To Bin'),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Location ID'),
        ),
        migrations.AlterField(
            model_name='sku',
            name='track_by',
            field=models.CharField(default='NONE', max_length=50, verbose_name='Tracking Method'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='State'),
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('COMPLETE', 'Complete'), ('CLOSED', 'Closed'), ('CANCELLED', 'Canceled')], default='OPEN', max_length=20, verbose_name='Status')),
                ('transaction_id', models.CharField(max_length=100, unique=True, verbose_name='Transaction ID')),
                ('reference_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Reference Number')),
                ('arrival_date', models.DateTimeField(blank=True, null=True, verbose_name='Arrival Date')),
                ('expected_arrival_date', models.DateTimeField(blank=True, null=True, verbose_name='Expected Arrival Date')),
                ('trailer_pro_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Trailer/Pro Number')),
                ('purchase_order_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Purchase Order Number')),
                ('receipt_advice_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Receipt Advice Number')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='warehouses.client', verbose_name='Customer')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='receipts', to='warehouses.warehouse', verbose_name='Warehouse')),
            ],
            options={
                'verbose_name': 'Receipt',
                'verbose_name_plural': 'Receipts',
                'db_table': 'wms_receipt',
            },
        ),
        migrations.CreateModel(
            name='ReceiptItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('qty', models.IntegerField(verbose_name='Qty (Pallet)')),
                ('weight_lbs', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='Weight (lbs)')),
                ('lot_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Lot Number')),
                ('expiration_date', models.DateField(blank=True, null=True, verbose_name='Expiration Date')),
                ('mu_label', models.CharField(blank=True, max_length=100, null=True, verbose_name='Select MU Label')),
                ('split_mu', models.BooleanField(default=False, verbose_name='Split Movable Unit')),
                ('primary_units_per_mu', models.IntegerField(blank=True, null=True, verbose_name='Primary units per MU')),
                ('mu_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='Movable Unit Type')),
                ('length_in', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Length (in.)')),
                ('width_in', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Width (in.)')),
                ('height_in', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Height (in.)')),
                ('mu_weight_lbs', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='MU Weight (lbs)')),
                ('is_on_hold', models.BooleanField(default=False, verbose_name='Put item on hold')),
                ('custom_fields', models.JSONField(blank=True, default=dict, verbose_name='Custom Fields')),
                ('putaway_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='putaway_receipt_items', to='warehouses.location', verbose_name='Putaway Location')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='warehouses.receipt', verbose_name='Receipt')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='receipt_items', to='warehouses.sku', verbose_name='SKU')),
            ],
            options={
                'verbose_name': 'Receipt Item',
                'verbose_name_plural': 'Receipt Items',
                'db_table': 'wms_receipt_item',
            },
        ),
    ]
