# Generated by Django 5.2.13 on 2026-04-22 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0005_alter_inventory_options_alter_inventory_bin_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='outboundorderitem',
            options={},
        ),
        migrations.AlterModelOptions(
            name='receiptitem',
            options={},
        ),
        migrations.RemoveField(
            model_name='outboundorder',
            name='contact_code',
        ),
        migrations.RemoveField(
            model_name='outboundorder',
            name='customer_name',
        ),
        migrations.RemoveField(
            model_name='outboundorder',
            name='delivery_confirmation',
        ),
        migrations.RemoveField(
            model_name='outboundorder',
            name='dry_weight',
        ),
        migrations.RemoveField(
            model_name='outboundorder',
            name='insurance_type',
        ),
        migrations.RemoveField(
            model_name='outboundorder',
            name='intl_contents_type',
        ),
        migrations.RemoveField(
            model_name='outboundorder',
            name='intl_non_delivery',
        ),
        migrations.RemoveField(
            model_name='outboundorder',
            name='warehouse_name',
        ),
        migrations.RemoveField(
            model_name='outboundorderitem',
            name='picked_qty',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='outboundorder',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Company Name'),
        ),
        migrations.AddField(
            model_name='outboundorder',
            name='mu_uom',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Movable Unit UOM'),
        ),
        migrations.AddField(
            model_name='outboundorder',
            name='total_movable_units',
            field=models.IntegerField(default=0, verbose_name='Total Movable Units'),
        ),
        migrations.AddField(
            model_name='outboundorder',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='orders', to='warehouses.warehouse', verbose_name='Warehouse'),
        ),
        migrations.AlterField(
            model_name='outboundorder',
            name='account_zip',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Account Zip/Postal'),
        ),
        migrations.AlterField(
            model_name='outboundorder',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='City/Township'),
        ),
        migrations.AlterField(
            model_name='outboundorder',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='outboundorder',
            name='insurance_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Insurance Amount'),
        ),
        migrations.AlterField(
            model_name='outboundorder',
            name='pickup_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Pickup Date/Time'),
        ),
        migrations.AlterField(
            model_name='outboundorder',
            name='postal_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Zip/Postal'),
        ),
        migrations.AlterField(
            model_name='outboundorder',
            name='purchase_order',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Purchase Order'),
        ),
        migrations.AlterField(
            model_name='outboundorder',
            name='require_return_receipt',
            field=models.BooleanField(default=False, verbose_name='Require return receipt'),
        ),
        migrations.AlterField(
            model_name='outboundorder',
            name='residential_delivery',
            field=models.BooleanField(default=False, verbose_name='Residential delivery'),
        ),
        migrations.AlterField(
            model_name='outboundorder',
            name='saturday_delivery',
            field=models.BooleanField(default=False, verbose_name='Saturday delivery'),
        ),
        migrations.AlterField(
            model_name='outboundorder',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='State/Province'),
        ),
        migrations.AlterField(
            model_name='outboundorder',
            name='total_packages',
            field=models.IntegerField(default=0, verbose_name='Total Packages'),
        ),
        migrations.AlterField(
            model_name='outboundorder',
            name='total_volume',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12, verbose_name='Total Volume cu ft'),
        ),
        migrations.AlterField(
            model_name='outboundorder',
            name='total_weight',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12, verbose_name='Total Weight lbs'),
        ),
        migrations.AlterField(
            model_name='outboundorder',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Transaction ID'),
        ),
        migrations.AlterField(
            model_name='outboundorder',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='outboundorderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='warehouses.outboundorder'),
        ),
        migrations.AlterField(
            model_name='outboundorderitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='outboundorderitem',
            name='sku',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='order_items', to='warehouses.sku'),
        ),
        migrations.AlterField(
            model_name='outboundorderitem',
            name='uom',
            field=models.CharField(default='Each', max_length=50, verbose_name='Primary Units'),
        ),
        migrations.AlterField(
            model_name='outboundorderitem',
            name='volume',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='outboundorderitem',
            name='weight',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Transaction ID'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='receipts', to='warehouses.warehouse', verbose_name='Warehouse'),
        ),
        migrations.AlterField(
            model_name='receiptitem',
            name='custom_fields',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='receiptitem',
            name='expiration_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='receiptitem',
            name='height_in',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='receiptitem',
            name='is_on_hold',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='receiptitem',
            name='length_in',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='receiptitem',
            name='lot_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='receiptitem',
            name='mu_label',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='MU Label'),
        ),
        migrations.AlterField(
            model_name='receiptitem',
            name='mu_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='receiptitem',
            name='mu_weight_lbs',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='receiptitem',
            name='primary_units_per_mu',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='receiptitem',
            name='putaway_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehouses.location'),
        ),
        migrations.AlterField(
            model_name='receiptitem',
            name='receipt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='warehouses.receipt'),
        ),
        migrations.AlterField(
            model_name='receiptitem',
            name='sku',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='receipt_items', to='warehouses.sku'),
        ),
        migrations.AlterField(
            model_name='receiptitem',
            name='split_mu',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='receiptitem',
            name='weight_lbs',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='receiptitem',
            name='width_in',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.DeleteModel(
            name='OrderCharge',
        ),
    ]
